### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by senier** [Componolit/BulkFuzz#4]
* `apps`
    * appid (Primary Key)
    * version
    * versioncode (Primary Key)
    * added
    * lastupdated
    * name
    * summary
    * desc
    * license
    * categories
    * category
    * source
    * tracker
    * marketversion
    * marketvercode
    * antifeatures
    * apkname
    * srcname
    * hash
    * hashtype
    * size
    * sdkver
    * targetSdkVersion
    * added_version
    * sig
    * permissions
    * nativecode

* `results`
    * resultsid (Primary Key)
    * appid
    * versioncode
    * timestamp
    * result

**Comment by senier** [comment]
@2xlink: You showed me an XML file with all the information in the package index. Can you please add the additional fields we want in the database above? Starting from there we can create a database schema.

**Comment by 2xlink** [comment]
I removed the appversion column in the `apps` table, as the information about the versions is already in `results`. 

Pulling should now work by: 
1. If the application is new, insert its metadata into `apps`, and all its appversions into `results`, with the result `to_be_tested`.
2. If the application is not new, but new versions are found then insert all new versions into `results`, with the result `to_be_tested`.
3. Else maybe update metadata, but don't insert anything into `results`.

**Comment by senier** [comment]
Thanks for updating!

I believe we will need the appversion column in the `apps` table. Think of situations where details like license, source code location etc. change. If we don't have multiple entries for different versions in the `apps` table, we won't be able to map our test results back to the real app details. Do you agree?

The workflow would then be:

1. For a new application _version_ (which could also be the first one in the store, i.e. a new app), create an entry in the `apps` table and in the `results` table, with result `to_be_tested`
2. Select all elements `results` where `result == to_be_tested` and pass their appid and appversion to the test class

**Comment by 2xlink** [comment]
Yeah, thats true. I will create the database schema with your comment in mind.
I also renamed `appversion` to `version` and added `hashtype` and `targetSdkVersion` as fields to the table `results`.

**Comment by senier** [comment]
Done.
